--
-- SQ_CODICE_RICHIESTA  (Sequence) 
--
CREATE SEQUENCE RINF_AMMINISTRAZIONE_EVO.SQ_CODICE_RICHIESTA
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  GLOBAL;


GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.SQ_CODICE_RICHIESTA TO APPL_RINF_EVO;

GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.SQ_CODICE_RICHIESTA TO RINF_GESTIONE_DB;
