--
-- SQ_CODICE_AUTORIZZAZIONE  (Sequence) 
--
CREATE SEQUENCE RINF_AMMINISTRAZIONE_EVO.SQ_CODICE_AUTORIZZAZIONE
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  GLOBAL;


GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.SQ_CODICE_AUTORIZZAZIONE TO APPL_RINF_EVO;

GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.SQ_CODICE_AUTORIZZAZIONE TO RINF_GESTIONE_DB;
