--
-- AGGIORNA_CACHE  (Table) 
--
CREATE TABLE APPL_RINF_EVO.AGGIORNA_CACHE
(
  STATO          NUMBER,
  NOME_MACCHINA  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE APPL_RINF_EVO.AGGIORNA_CACHE IS 'Tabella per la gestione della cache di memoria dell''applicazione';

COMMENT ON COLUMN APPL_RINF_EVO.AGGIORNA_CACHE.STATO IS '0: Fatto, 1: da Fare';
