--
-- LOG_HISTORY  (Table) 
--
CREATE TABLE APPL_RINF_EVO.LOG_HISTORY
(
  ID_LOG           NUMBER,
  CODICE_ATTIVITA  NUMBER,
  DATA_ATTIVITA    DATE,
  TESTO            CLOB,
  ID_UTENTE        NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE;


--
-- PK_LOGHISTORY  (Index) 
--
CREATE UNIQUE INDEX APPL_RINF_EVO.PK_LOGHISTORY ON APPL_RINF_EVO.LOG_HISTORY
(ID_LOG)
LOGGING;

ALTER TABLE APPL_RINF_EVO.LOG_HISTORY ADD (
  CONSTRAINT PK_LOGHISTORY
  PRIMARY KEY
  (ID_LOG)
  USING INDEX APPL_RINF_EVO.PK_LOGHISTORY
  ENABLE VALIDATE);



--
-- IDX_LOGHISTCODATTIVITA  (Index) 
--
CREATE INDEX APPL_RINF_EVO.IDX_LOGHISTCODATTIVITA ON APPL_RINF_EVO.LOG_HISTORY
(CODICE_ATTIVITA)
LOGGING;
