--
-- PROCESS_STATUS  (Table) 
--
CREATE TABLE APPL_RINF_EVO.PROCESS_STATUS
(
  TRAN_ID       VARCHAR2(200 BYTE)              NOT NULL,
  MESSAGE       VARCHAR2(200 BYTE),
  STEP          INTEGER                         NOT NULL,
  STEP_OF       INTEGER,
  INDEX_CORR    INTEGER,
  INDEX_OF      INTEGER,
  CODICE_ESITO  INTEGER,
  DATA          DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE;
