--
-- REGISTRO_SEDI_ELIMINATE_NUOVE  (Table) 
--
CREATE TABLE APPL_RINF_EVO.REGISTRO_SEDI_ELIMINATE_NUOVE
(
  CODICE_VERSIONE        NUMBER,
  CODICE_AUTORIZZAZIONE  NUMBER,
  CODICE_DTP             VARCHAR2(4 BYTE),
  SEDE_TECNICA           VARCHAR2(6 BYTE),
  DEFINIZIONE            VARCHAR2(200 BYTE),
  FLAG_TIPO              NUMBER,
  ST_TIPOLOGIA           VARCHAR2(15 BYTE),
  DATA_INSERIMENTO       DATE,
  STATO_SISTEMA          VARCHAR2(50 BYTE),
  STATO_UTENTE           VARCHAR2(50 BYTE),
  FLAG_STATO_FINALE      NUMBER,
  STATO_FINALE           VARCHAR2(15 BYTE),
  DATA_AGGIORNAMENTO     DATE,
  CODICE_VERSIONE_PUB    NUMBER,
  DOIT                   VARCHAR2(20 BYTE),
  DCO                    VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;
