--
-- SCHEMA_METADATA  (Table) 
--
CREATE TABLE APPL_RINF_EVO.SCHEMA_METADATA
(
  OWNER          CHAR(13 BYTE),
  OBJECT_TYPE    VARCHAR2(23 BYTE),
  OBJECT_NAME    VARCHAR2(128 BYTE),
  OBJECT_ID      NUMBER,
  LAST_DDL_TIME  DATE,
  META_LENGTH    NUMBER,
  META_DATA      CLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE;
