--
-- SEMAFORO  (Table) 
--
CREATE TABLE APPL_RINF_EVO.SEMAFORO
(
  ID                  NUMBER,
  STATO               NUMBER,
  DATA_CREAZIONE      DATE,
  DATA_AGGIORNAMENTO  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE APPL_RINF_EVO.SEMAFORO IS 'Tabella per la gestione dei semafori dell''applicazione. Valori di configurazione di sistema, precaricati.';

COMMENT ON COLUMN APPL_RINF_EVO.SEMAFORO.STATO IS '0=ROSSO, 1=VERDE';


--
-- PK_SEMAFORO  (Index) 
--
CREATE UNIQUE INDEX APPL_RINF_EVO.PK_SEMAFORO ON APPL_RINF_EVO.SEMAFORO
(ID)
LOGGING;

ALTER TABLE APPL_RINF_EVO.SEMAFORO ADD (
  CONSTRAINT PK_SEMAFORO
  PRIMARY KEY
  (ID)
  USING INDEX APPL_RINF_EVO.PK_SEMAFORO
  ENABLE VALIDATE);

