--
-- T_LOG_CHIAMATE  (Table) 
--
CREATE TABLE APPL_RINF_EVO.T_LOG_CHIAMATE
(
  PARAMETRI  VARCHAR2(2999 BYTE),
  DATETIME   DATE                               DEFAULT sysdate
)
LOGGING 
NOCOMPRESS 
NOCACHE;
