--
-- ANAG_RICH_AUTORIZZAZIONI_IDX  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.ANAG_RICH_AUTORIZZAZIONI_IDX ON RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI
(CODICE_STATO_RICHIESTA)
LOGGING;
