--
-- DETTAGLIO_AUTORIZZAZIONI_IDX  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI_IDX ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI
(CODICE_STATO_RICHIESTA)
LOGGING;
