--
-- IDX_ANAG_RICH_AUT_01  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.IDX_ANAG_RICH_AUT_01 ON RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI
(CODICE_RICHIESTA, DATA_RICHIESTA, DATA_SCADENZA, CODICE_STATO_RICHIESTA, NOTE, 
DATA_CHIUSURA)
LOGGING;
