--
-- IDX_DETT_AUTO_01  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.IDX_DETT_AUTO_01 ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI
(CODICE_RICHIESTA, CODICE_DTP, FLAG_SEDE_CENTRALE, CODICE_STATO_RICHIESTA, DATA_AUTORIZZAZIONE)
LOGGING;
