--
-- PK_DETTAGLIOAUTORIZZAZIONI  (Index) 
--
CREATE UNIQUE INDEX RINF_AMMINISTRAZIONE_EVO.PK_DETTAGLIOAUTORIZZAZIONI ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI
(CODICE_RICHIESTA, ID_UTENTE, FLAG_SEDE_CENTRALE, CODICE_DTP)
LOGGING;
