--
-- FNC_ISNUMBER  (Function) 
--
CREATE OR REPLACE FUNCTION APPL_RINF_EVO."FNC_ISNUMBER" (stringa varchar2) RETURN VARCHAR2 IS
numero NUMBER;

BEGIN
   select TO_NUMBER(stringa) into numero from dual;
   RETURN 'TRUE';
   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       NULL;
     WHEN OTHERS THEN
       RETURN 'FALSE';
END FNC_ISNUMBER;


/


GRANT EXECUTE ON APPL_RINF_EVO.FNC_ISNUMBER TO PUBLIC;
