--
-- ANAG_PRIORITA  (Table) 
--
CREATE TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA
(
  CODICE_PRIORITA  NUMBER,
  DESCRIZIONE      VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA IS 'Anagrafica delle priorità delle richieste informazioni. Valori di configurazione di sistema, precaricati.';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA.CODICE_PRIORITA IS 'Identificativo numerico della priorità';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA.DESCRIZIONE IS 'Descrizione della priorità';


--
-- PK_ANAGPRIORITA  (Index) 
--
CREATE UNIQUE INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGPRIORITA ON RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA
(CODICE_PRIORITA)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA ADD (
  CONSTRAINT PK_ANAGPRIORITA
  PRIMARY KEY
  (CODICE_PRIORITA)
  USING INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGPRIORITA
  ENABLE VALIDATE);



GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA TO APPL_RINF_EVO;

GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA TO RINF_GESTIONE_DB;
