--
-- ANAG_STATO_AUTORIZZAZIONE  (Table) 
--
CREATE TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE
(
  CODICE_STATO_RICHIESTA  NUMBER,
  DESCRIZIONE             VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE IS 'Anagrafica dello stato della richiesta autorizzazioni.Valori di configurazione di sistema, precaricati.';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE.CODICE_STATO_RICHIESTA IS 'Identificativo numerico dello stato della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE.DESCRIZIONE IS 'Descrizione  dello stato della richiesta';


--
-- PK_ANAGSTATOAUTRIZZ  (Index) 
--
CREATE UNIQUE INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGSTATOAUTRIZZ ON RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE
(CODICE_STATO_RICHIESTA)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE ADD (
  CONSTRAINT PK_ANAGSTATOAUTRIZZ
  PRIMARY KEY
  (CODICE_STATO_RICHIESTA)
  USING INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGSTATOAUTRIZZ
  ENABLE VALIDATE);



GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE TO APPL_RINF_EVO;

GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE TO RINF_GESTIONE_DB;
