--
-- ANAG_STATO_RICHIESTA  (Table) 
--
CREATE TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA
(
  CODICE_STATO  NUMBER,
  DESCRIZIONE   VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA IS 'Anagrafica degli stati delle richieste informazioni.Valori di configurazione di sistema, precaricati.';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA.CODICE_STATO IS 'Identificativo numerico dello stato della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA.DESCRIZIONE IS 'Descrizione dello stato della richiesta';


--
-- PK_ANAGSTATORICHIESTA  (Index) 
--
CREATE UNIQUE INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGSTATORICHIESTA ON RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA
(CODICE_STATO)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA ADD (
  CONSTRAINT PK_ANAGSTATORICHIESTA
  PRIMARY KEY
  (CODICE_STATO)
  USING INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGSTATORICHIESTA
  ENABLE VALIDATE);



GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA TO APPL_RINF_EVO;

GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA TO RINF_GESTIONE_DB;
