--
-- ANAG_RICHIESTE_AUTORIZZAZIONI  (Table) 
--
CREATE TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI
(
  CODICE_RICHIESTA        NUMBER,
  DATA_RICHIESTA          DATE,
  DATA_SCADENZA           DATE,
  CODICE_STATO_RICHIESTA  NUMBER,
  NOTE                    VARCHAR2(2000 BYTE),
  DATA_CHIUSURA           DATE,
  DATA_RIFERIMENTO        DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI IS 'Anagrafica delle richieste autorizzazioni effettuate dall''amministratore';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI.CODICE_RICHIESTA IS 'Identificativo numerico della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI.DATA_RICHIESTA IS 'Data in cui è stata effettuata la richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI.DATA_SCADENZA IS 'Data entro cui i Validatori Territoriali/SC dovranno autorizzare i dati di propria competenza';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI.CODICE_STATO_RICHIESTA IS 'Identificativo numerico dello stato della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI.DATA_CHIUSURA IS 'Data della chiusura della richiesta';


--
-- PK_ANAGRICHIESTAAUTOR  (Index) 
--
CREATE UNIQUE INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGRICHIESTAAUTOR ON RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI
(CODICE_RICHIESTA)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI ADD (
  CONSTRAINT PK_ANAGRICHIESTAAUTOR
  PRIMARY KEY
  (CODICE_RICHIESTA)
  USING INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGRICHIESTAAUTOR
  ENABLE VALIDATE);



--
-- ANAG_RICH_AUTORIZZAZIONI_IDX  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.ANAG_RICH_AUTORIZZAZIONI_IDX ON RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI
(CODICE_STATO_RICHIESTA)
LOGGING;

--
-- IDX_ANAG_RICH_AUT_01  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.IDX_ANAG_RICH_AUT_01 ON RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI
(CODICE_RICHIESTA, DATA_RICHIESTA, DATA_SCADENZA, CODICE_STATO_RICHIESTA, NOTE, 
DATA_CHIUSURA)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI ADD (
  CONSTRAINT FK_RICHIESTEAUTOR_STATOAUTO 
  FOREIGN KEY (CODICE_STATO_RICHIESTA) 
  REFERENCES RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE (CODICE_STATO_RICHIESTA)
  ENABLE VALIDATE);



GRANT DELETE, INSERT, SELECT, UPDATE ON RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI TO APPL_RINF_EVO;

GRANT REFERENCES, SELECT ON RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI TO RINF_AUTORIZZAZIONI_EVO;

GRANT DELETE, INSERT, SELECT, UPDATE ON RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI TO RINF_GESTIONE_DB;
