--
-- ANAG_TIPO_RICHIESTA  (Table) 
--
CREATE TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA
(
  CODICE_TIPO  NUMBER,
  DESCRIZIONE  VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA IS 'Anagrafica delle tipologie delle richieste informazioni.Valori di configurazione di sistema, precaricati.';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA.CODICE_TIPO IS 'Identificativo numerico del tipo della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA.DESCRIZIONE IS 'Descrizione del tipo della richiesta';


--
-- PK_ANAGTIPORICHIESTA  (Index) 
--
CREATE UNIQUE INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGTIPORICHIESTA ON RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA
(CODICE_TIPO)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA ADD (
  CONSTRAINT PK_ANAGTIPORICHIESTA
  PRIMARY KEY
  (CODICE_TIPO)
  USING INDEX RINF_AMMINISTRAZIONE_EVO.PK_ANAGTIPORICHIESTA
  ENABLE VALIDATE);



GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA TO APPL_RINF_EVO;

GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA TO RINF_GESTIONE_DB;
