--
-- DETTAGLIO_AUTORIZZAZIONI  (Table) 
--
CREATE TABLE RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI
(
  CODICE_RICHIESTA        NUMBER,
  ID_UTENTE               NUMBER,
  FLAG_SEDE_CENTRALE      NUMBER,
  CODICE_DTP              VARCHAR2(10 BYTE),
  TOTALE_SOL              NUMBER,
  TOTALE_OP               NUMBER,
  CODICE_STATO_RICHIESTA  NUMBER,
  DATA_AUTORIZZAZIONE     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI IS 'Dettaglio della richiesta di autorizzazione';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI.CODICE_RICHIESTA IS 'Identificativo numerico della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI.ID_UTENTE IS 'Identificativo dell''utente al quale la richiesta è stata inoltrata';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI.FLAG_SEDE_CENTRALE IS 'Flag Utente Validatoridi Sede Centrale 0=NO, 1=SI';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI.CODICE_DTP IS 'Identificativo della DTP dell''utente/dei dati da validare';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI.TOTALE_SOL IS 'Totale delle SOL da validare';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI.TOTALE_OP IS 'Totale delle OP da validare';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI.CODICE_STATO_RICHIESTA IS 'Identificativo numerico dello stato della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI.DATA_AUTORIZZAZIONE IS 'Data di autorizzazione della richiesta';


--
-- PK_DETTAGLIOAUTORIZZAZIONI  (Index) 
--
CREATE UNIQUE INDEX RINF_AMMINISTRAZIONE_EVO.PK_DETTAGLIOAUTORIZZAZIONI ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI
(CODICE_RICHIESTA, ID_UTENTE, FLAG_SEDE_CENTRALE, CODICE_DTP)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI ADD (
  CONSTRAINT PK_DETTAGLIOAUTORIZZAZIONI
  PRIMARY KEY
  (CODICE_RICHIESTA, ID_UTENTE, FLAG_SEDE_CENTRALE, CODICE_DTP)
  USING INDEX RINF_AMMINISTRAZIONE_EVO.PK_DETTAGLIOAUTORIZZAZIONI
  ENABLE VALIDATE);



--
-- DETTAGLIO_AUTORIZZAZIONI_IDX  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI_IDX ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI
(CODICE_STATO_RICHIESTA)
LOGGING;

--
-- IDX_DETTAGLIO_AUTO_01  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.IDX_DETTAGLIO_AUTO_01 ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI
(ID_UTENTE)
LOGGING;

--
-- IDX_DETT_AUTO_01  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.IDX_DETT_AUTO_01 ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI
(CODICE_RICHIESTA, CODICE_DTP, FLAG_SEDE_CENTRALE, CODICE_STATO_RICHIESTA, DATA_AUTORIZZAZIONE)
LOGGING;

--
-- IDX_DETT_AUT_01  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.IDX_DETT_AUT_01 ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI
(CODICE_DTP)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI ADD (
  CONSTRAINT FK_DETTAAUTOR_STATOAUTO 
  FOREIGN KEY (CODICE_STATO_RICHIESTA) 
  REFERENCES RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_AUTORIZZAZIONE (CODICE_STATO_RICHIESTA)
  ENABLE VALIDATE);

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI ADD (
  CONSTRAINT FK_DETTAUTOR_ANAGDTP 
  FOREIGN KEY (CODICE_DTP) 
  REFERENCES RINF_ANAGRAFICHE_EVO.ANAG_DTP (CODICE_DTP)
  ENABLE NOVALIDATE);

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI ADD (
  CONSTRAINT FK_DETTAUTOR_ANAGUTENTE 
  FOREIGN KEY (ID_UTENTE) 
  REFERENCES RINF_SICUREZZA_EVO.ANAG_UTENTE (ID_UTENTE)
  ENABLE NOVALIDATE);



GRANT DELETE, INSERT, SELECT, UPDATE ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI TO APPL_RINF_EVO;

GRANT DELETE, INSERT, SELECT, UPDATE ON RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI TO RINF_GESTIONE_DB;
