--
-- RICHIESTE_INFORMAZIONE  (Table) 
--
CREATE TABLE RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE
(
  CODICE_RICHIESTA  NUMBER,
  DATA_RICHIESTA    DATE,
  ID_UTENTE         NUMBER,
  OGGETTO           VARCHAR2(1000 BYTE),
  TESTO             CLOB,
  EMAIL_MITTENTE    VARCHAR2(500 BYTE),
  CODICE_PRIORITA   NUMBER,
  CODICE_STATO      NUMBER,
  CODICE_TIPO       NUMBER,
  DATA_EVASIONE     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE IS 'Anagrafica delle richieste informazioni';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.CODICE_RICHIESTA IS 'Identificativo numerico della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.DATA_RICHIESTA IS 'Data della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.ID_UTENTE IS 'Codice utente mittente della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.OGGETTO IS 'Oggetto della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.TESTO IS 'Testo della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.EMAIL_MITTENTE IS 'Email dell''utente mittente della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.CODICE_PRIORITA IS 'Identificativo della priorità della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.CODICE_STATO IS 'Identificativo dello stato della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.CODICE_TIPO IS 'Identificativo del tipo della richiesta';

COMMENT ON COLUMN RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE.DATA_EVASIONE IS 'Data chiusura della richiesta';


--
-- PK_RICHIESTEINFORMAZIONE  (Index) 
--
CREATE UNIQUE INDEX RINF_AMMINISTRAZIONE_EVO.PK_RICHIESTEINFORMAZIONE ON RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE
(CODICE_RICHIESTA)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE ADD (
  CONSTRAINT PK_RICHIESTEINFORMAZIONE
  PRIMARY KEY
  (CODICE_RICHIESTA)
  USING INDEX RINF_AMMINISTRAZIONE_EVO.PK_RICHIESTEINFORMAZIONE
  ENABLE VALIDATE);



--
-- RICHIESTE_INFORMAZIONE_IDX  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE_IDX ON RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE
(CODICE_PRIORITA)
LOGGING;

--
-- RICHIESTE_INFORMAZIONE_IDX1  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE_IDX1 ON RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE
(CODICE_STATO)
LOGGING;

--
-- RICHIESTE_INFORMAZIONE_IDX2  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE_IDX2 ON RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE
(CODICE_TIPO)
LOGGING;

--
-- RICHIESTE_INFORMAZIONE_01  (Index) 
--
CREATE INDEX RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE_01 ON RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE
(ID_UTENTE)
LOGGING;

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE ADD (
  CONSTRAINT FK_RICHIESTE_PRIORITA 
  FOREIGN KEY (CODICE_PRIORITA) 
  REFERENCES RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA (CODICE_PRIORITA)
  ENABLE VALIDATE);

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE ADD (
  CONSTRAINT FK_RICHIESTE_STATO 
  FOREIGN KEY (CODICE_STATO) 
  REFERENCES RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA (CODICE_STATO)
  ENABLE VALIDATE);

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE ADD (
  CONSTRAINT FK_RICHIESTE_TIPO 
  FOREIGN KEY (CODICE_TIPO) 
  REFERENCES RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA (CODICE_TIPO)
  ENABLE VALIDATE);

ALTER TABLE RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE ADD (
  CONSTRAINT FK_RICHIESTE_UTENTI 
  FOREIGN KEY (ID_UTENTE) 
  REFERENCES RINF_SICUREZZA_EVO.ANAG_UTENTE (ID_UTENTE)
  ENABLE NOVALIDATE);



GRANT DELETE, INSERT, SELECT, UPDATE ON RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE TO APPL_RINF_EVO;

GRANT DELETE, INSERT, SELECT, UPDATE ON RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE TO RINF_GESTIONE_DB;
