--
-- V_STATO_RICHIESTE  (View) 
--
CREATE OR REPLACE VIEW RINF_AMMINISTRAZIONE_EVO.V_STATO_RICHIESTE
(CODICE_RICHIESTA, DATA_RICHIESTA, DATA_SCADENZA, STATO_FINALE, NOTE, 
 DATA_CHIUSURA, CODICE_DTP, DESCRIZIONE_DTP, CODICE_STATO_RICHIESTA, DATA_AUTORIZZAZIONE, 
 FLAG_SEDE_CENTRALE)
BEQUEATH DEFINER
AS 
SELECT r.CODICE_RICHIESTA,
          r.DATA_RICHIESTA,
          r.DATA_SCADENZA,
          r.CODICE_STATO_RICHIESTA STATO_FINALE,
          r.NOTE,
          r.DATA_CHIUSURA,
          s.CODICE_DTP,
          DESCRIZIONE_DTP,
          S.CODICE_STATO_RICHIESTA,
          s.DATA_AUTORIZZAZIONE,
          s.FLAG_SEDE_CENTRALE
     FROM RINF_AMMINISTRAZIONE_EVO.ANAG_RICHIESTE_AUTORIZZAZIONI r,
          (  SELECT CODICE_RICHIESTA,
                    c.CODICE_DTP,
                    d.DESCRIZIONE DESCRIZIONE_DTP,
                    FLAG_SEDE_CENTRALE,
                    MAX (CODICE_STATO_RICHIESTA) CODICE_STATO_RICHIESTA,
                    MAX (DATA_AUTORIZZAZIONE) DATA_AUTORIZZAZIONE
               FROM RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI c,
                    RINF_ANAGRAFICHE_EVO.ANAG_DTP d
              WHERE FLAG_SEDE_CENTRALE = 0 AND d.CODICE_DTP = c.CODICE_DTP
           GROUP BY CODICE_RICHIESTA,
                    c.CODICE_DTP,
                    d.DESCRIZIONE,
                    FLAG_SEDE_CENTRALE
           UNION
             SELECT CODICE_RICHIESTA,
                    CODICE_DTP,
                    'Sede Centrale:' || SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO FLAG_SEDE_CENTRALE,
                    MAX (CODICE_STATO_RICHIESTA),
                    MAX (DATA_AUTORIZZAZIONE)
               FROM RINF_AMMINISTRAZIONE_EVO.DETTAGLIO_AUTORIZZAZIONI a,
                    RINF_SICUREZZA_EVO.ANAG_TIPO_DEPOSITARIO d
              WHERE     D.CODICE_TIPO_DEPOSITARIO = A.FLAG_SEDE_CENTRALE
                    AND FLAG_SEDE_CENTRALE <> 0
           GROUP BY CODICE_RICHIESTA,
                    CODICE_DTP,
                    SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO) s
    WHERE r.CODICE_RICHIESTA = s.CODICE_RICHIESTA;


GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.V_STATO_RICHIESTE TO APPL_RINF_EVO;

GRANT SELECT ON RINF_AMMINISTRAZIONE_EVO.V_STATO_RICHIESTE TO RINF_GESTIONE_DB;
