--
-- V_STATO_RICHIESTE_AUTORIZ  (View) 
--
CREATE OR REPLACE VIEW RINF_AMMINISTRAZIONE_EVO.V_STATO_RICHIESTE_AUTORIZ
(CODICE_RICHIESTA, DATA_RICHIESTA, DATA_SCADENZA, STATO_FINALE, NOTE, 
 DATA_CHIUSURA, CODICE_DTP, DESCRIZIONE_DTP, CODICE_TERR, FLAG_NEW_TERRITORIO, 
 DATA_AUTORIZZAZIONE_TERRITOTIO, CODICE_DTEC, FLAG_DTEC, DATA_AUTORIZZAZIONE_DTEC, CODICE_DTEC_2, 
 FLAG_DTEC_2, DATA_AUTORIZZAZIONE_DTEC_2, CODICE_DTEC_3, FLAG_DTEC_3, DATA_AUTORIZZAZIONE_DTEC_3, 
 CODICE_DCO, FLAG_DCO, DATA_AUTORIZZAZIONE_DCO, CODICE_DSPS, FLAG_DSPS, 
 DATA_AUTORIZZAZIONE_DSPS)
BEQUEATH DEFINER
AS 
Select r.CODICE_RICHIESTA,
          r.DATA_RICHIESTA,
          r.DATA_SCADENZA,
          r.CODICE_STATO_RICHIESTA STATO_FINALE,
          r.NOTE,
          r.DATA_CHIUSURA,
          s1.CODICE_DTP,
          DESCRIZIONE_DTP,
		  s1.FLAG_SEDE_CENTRALE CODICE_TERR,
          s1.CODICE_STATO_RICHIESTA FLAG_new_territorio,
          s1.DATA_AUTORIZZAZIONE DATA_AUTORIZZAZIONE_territotio,
		  s2.FLAG_SEDE_CENTRALE CODICE_DTEC,
          s2.CODICE_STATO_RICHIESTA FLAG_DTEC,
          s2.DATA_AUTORIZZAZIONE DATA_AUTORIZZAZIONE_DTEC,
		  s3.FLAG_SEDE_CENTRALE CODICE_DTEC_2,
          s3.CODICE_STATO_RICHIESTA FLAG_DTEC_2,
          s3.DATA_AUTORIZZAZIONE DATA_AUTORIZZAZIONE_DTEC_2,
		  s4.FLAG_SEDE_CENTRALE CODICE_DTEC_3,
          s4.CODICE_STATO_RICHIESTA FLAG_DTEC_3,
          s4.DATA_AUTORIZZAZIONE DATA_AUTORIZZAZIONE_DTEC_3,
		  s5.FLAG_SEDE_CENTRALE CODICE_DCO,
          s5.CODICE_STATO_RICHIESTA FLAG_DCO,
          s5.DATA_AUTORIZZAZIONE DATA_AUTORIZZAZIONE_DCO,
		  s6.FLAG_SEDE_CENTRALE CODICE_DSPS,
          s6.CODICE_STATO_RICHIESTA FLAG_DSPS,
          s6.DATA_AUTORIZZAZIONE DATA_AUTORIZZAZIONE_DSPS
--
     From Rinf_Amministrazione_Evo.ANAG_RICHIESTE_AUTORIZZAZIONI r,
          (  Select CODICE_RICHIESTA,
                    c.CODICE_DTP,
                    d.DESCRIZIONE DESCRIZIONE_DTP,
                    FLAG_SEDE_CENTRALE,
                    Max (CODICE_STATO_RICHIESTA) CODICE_STATO_RICHIESTA,
                    Max (DATA_AUTORIZZAZIONE) DATA_AUTORIZZAZIONE
               From Rinf_Amministrazione_Evo.DETTAGLIO_AUTORIZZAZIONI c,
                    Rinf_Anagrafiche_Evo.ANAG_DTP d
              Where FLAG_SEDE_CENTRALE = 0 
			    And d.CODICE_DTP = c.CODICE_DTP
           Group By CODICE_RICHIESTA,
                    c.CODICE_DTP,
                    d.DESCRIZIONE,
                    FLAG_SEDE_CENTRALE ) s1,
--
         (   Select CODICE_RICHIESTA,
                    CODICE_DTP,
                    'Sede Centrale:' || SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO FLAG_SEDE_CENTRALE,
                    Max (CODICE_STATO_RICHIESTA) CODICE_STATO_RICHIESTA,
                    Max (DATA_AUTORIZZAZIONE) DATA_AUTORIZZAZIONE
               From Rinf_Amministrazione_Evo.DETTAGLIO_AUTORIZZAZIONI c,
                    Rinf_Sicurezza_Evo.ANAG_TIPO_DEPOSITARIO d
              Where d.CODICE_TIPO_DEPOSITARIO = c.FLAG_SEDE_CENTRALE
                And FLAG_SEDE_CENTRALE = 2
           Group By CODICE_RICHIESTA,
                    CODICE_DTP,
                    SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO) s2,
--
         (   Select CODICE_RICHIESTA,
                    CODICE_DTP,
                    'Sede Centrale:' || SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO FLAG_SEDE_CENTRALE,
                    Max (CODICE_STATO_RICHIESTA) CODICE_STATO_RICHIESTA,
                    Max (DATA_AUTORIZZAZIONE) DATA_AUTORIZZAZIONE
               From Rinf_Amministrazione_Evo.DETTAGLIO_AUTORIZZAZIONI c,
                    Rinf_Sicurezza_Evo.ANAG_TIPO_DEPOSITARIO d
              Where d.CODICE_TIPO_DEPOSITARIO = c.FLAG_SEDE_CENTRALE
                And FLAG_SEDE_CENTRALE = 6
           Group By CODICE_RICHIESTA,
                    CODICE_DTP,
                    SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO) s3,
--
         (   Select CODICE_RICHIESTA,
                    CODICE_DTP,
                    'Sede Centrale:' || SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO FLAG_SEDE_CENTRALE,
                    Max (CODICE_STATO_RICHIESTA) CODICE_STATO_RICHIESTA,
                    Max (DATA_AUTORIZZAZIONE) DATA_AUTORIZZAZIONE
               From Rinf_Amministrazione_Evo.DETTAGLIO_AUTORIZZAZIONI c,
                    Rinf_Sicurezza_Evo.ANAG_TIPO_DEPOSITARIO d
              Where d.CODICE_TIPO_DEPOSITARIO = c.FLAG_SEDE_CENTRALE
                And FLAG_SEDE_CENTRALE = 7
           Group By CODICE_RICHIESTA,
                    CODICE_DTP,
                    SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO) s4,
--
         (   Select CODICE_RICHIESTA,
                    CODICE_DTP,
                    'Sede Centrale:' || SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO FLAG_SEDE_CENTRALE,
                    Max (CODICE_STATO_RICHIESTA) CODICE_STATO_RICHIESTA,
                    Max (DATA_AUTORIZZAZIONE) DATA_AUTORIZZAZIONE
               From Rinf_Amministrazione_Evo.DETTAGLIO_AUTORIZZAZIONI c,
                    Rinf_Sicurezza_Evo.ANAG_TIPO_DEPOSITARIO d
              Where d.CODICE_TIPO_DEPOSITARIO = c.FLAG_SEDE_CENTRALE
                And FLAG_SEDE_CENTRALE = 10
           Group By CODICE_RICHIESTA,
                    CODICE_DTP,
                    SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO) s5,
--
         (   Select CODICE_RICHIESTA,
                    CODICE_DTP,
                    'Sede Centrale:' || SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO FLAG_SEDE_CENTRALE,
                    Max (CODICE_STATO_RICHIESTA) CODICE_STATO_RICHIESTA,
                    Max (DATA_AUTORIZZAZIONE) DATA_AUTORIZZAZIONE
               From Rinf_Amministrazione_Evo.DETTAGLIO_AUTORIZZAZIONI c,
                    Rinf_Sicurezza_Evo.ANAG_TIPO_DEPOSITARIO d
              Where d.CODICE_TIPO_DEPOSITARIO = c.FLAG_SEDE_CENTRALE
                And FLAG_SEDE_CENTRALE = 11
           Group By CODICE_RICHIESTA,
                    CODICE_DTP,
                    SIGLA_TIPO_DEPOSITARIO,
                    CODICE_TIPO_DEPOSITARIO) s6
--
    Where r.CODICE_RICHIESTA = s1.CODICE_RICHIESTA
	  And r.CODICE_RICHIESTA = s2.CODICE_RICHIESTA
	  And r.CODICE_RICHIESTA = s3.CODICE_RICHIESTA
	  And r.CODICE_RICHIESTA = s4.CODICE_RICHIESTA
	  And r.CODICE_RICHIESTA = s5.CODICE_RICHIESTA
	  And r.CODICE_RICHIESTA = s6.CODICE_RICHIESTA
--	  And r.CODICE_RICHIESTA = (Select Max(CODICE_RICHIESTA) From Rinf_Amministrazione_Evo.ANAG_RICHIESTE_AUTORIZZAZIONI)
	  And s1.CODICE_DTP = s2.CODICE_DTP
	  And s2.CODICE_DTP = s3.CODICE_DTP
	  And s3.CODICE_DTP = s4.CODICE_DTP
	  And s4.CODICE_DTP = s5.CODICE_DTP
	  And s5.CODICE_DTP = s6.CODICE_DTP
--      And r.CODICE_STATO_RICHIESTA = 2
--      And r.codice_richiesta not in
--      (select distinct CODICE_AUTORIZZAZIONE FROM RINF_PUBBLICATI_EVO.VERSIONE_AUTORIZZAZIONI)

      order by r.codice_richiesta desc,  s1.CODICE_DTP;


GRANT REFERENCES, SELECT ON RINF_AMMINISTRAZIONE_EVO.V_STATO_RICHIESTE_AUTORIZ TO APPL_RINF_EVO;
