--
-- CHECK_RINFTABLES_COUNT_STATS  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.CHECK_RINFTABLES_COUNT_STATS
(OWNER, TABLE_NAME, NUM_ROWS, LAST_ANALYZED)
BEQUEATH DEFINER
AS 
select  OWNER, TABLE_NAME, NUM_ROWS, LAST_ANALYZED
from all_tables
where owner like '%RINF%'
--GROUP BY owner, table_name
ORDER BY 3 DESC;
