--
-- CHECK_ACQUISIZIONE_RINF_V  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.CHECK_ACQUISIZIONE_RINF_V
(ACQ_ID_LOG, ACQUISIZIONE, ACQ_ID_OPERATORE, ACQ_OPERATORE, ACQ_INIZIO, 
 ACQ_STEP1_FINE, ACQ_CONTROLLI_FINE, ACQ_FINE, ACQ_CACHE_FINE, ACQ_STEP1_DURATA, 
 ACQ_CONTROLLI_DURATA, ACQ_DURATA)
BEQUEATH DEFINER
AS 
SELECT
ACQUISIZIONE_INIZIO.ACQ_ID_LOG,
'Acquisizione del '||ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO    ACQUISIZIONE,
ACQUISIZIONE_INIZIO.ACQ_ID_OPERATORE,
ACQUISIZIONE_INIZIO.ACQ_OPERATORE,
TO_CHAR(ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO,'HH24:MI:SS')  ACQ_INIZIO,
TO_CHAR(ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE,'HH24:MI:SS')  ACQ_STEP1_FINE,
-- TRUNC((ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24) AS ore,
-- MOD(TRUNC((ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60), 60) AS minuti,
-- MOD(TRUNC((ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60 * 60), 60) AS secondi,
-- DECODE(ORE,0,MINUTI||' m. + '||SECONDI||' s.',ORE||' h. + '||MINUTI||' m. + '||SECONDI||' s.')   STEP1_DURATA,
TO_CHAR(ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE,'HH24:MI:SS')  ACQ_CONTROLLI_FINE,
TO_CHAR(ACQUISIZIONE_FINE.ACQ_DATA_FINE,'HH24:MI:SS')  ACQ_FINE,
TO_CHAR(ACQUISIZIONE_CACHE_FINE.ACQ_CACHE_DATA_FINE,'HH24:MI:SS')  ACQ_CACHE_FINE,
DECODE(TRUNC((ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24),0,MOD(TRUNC((ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60), 60)||' m. + '||MOD(TRUNC((ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60 * 60), 60)||' s.',TRUNC((ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24)||' h. + '||MOD(TRUNC((ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60), 60)||' m. + '||MOD(TRUNC((ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60 * 60), 60)||' s.')   ACQ_STEP1_DURATA,
-- TO_CHAR(ACQUISIZIONE_CONTROLLI_INIZIO.ACQ_CONTROLLI_DATA_INIZIO,'HH24:MI:SS')  ACQ_CONTROLLI_ORA_INIZIO,
-- TRUNC((ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE - ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE) * 24) AS ore,
-- MOD(TRUNC((ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE - ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE) * 24 * 60), 60) AS minuti,
-- MOD(TRUNC((ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE - ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE) * 24 * 60 * 60), 60) AS secondi,
DECODE(TRUNC((ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE - ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE) * 24),0,MOD(TRUNC((ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE - ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE) * 24 * 60), 60)||' m. + '||MOD(TRUNC((ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE - ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE) * 24 * 60 * 60), 60)||' s.',TRUNC((ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE - ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE) * 24)||' h. + '||MOD(TRUNC((ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE - ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE) * 24 * 60), 60)||' m. + '||MOD(TRUNC((ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE - ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE) * 24 * 60 * 60), 60)||' s.')   ACQ_CONTROLLI_DURATA,
DECODE(TRUNC((ACQUISIZIONE_CACHE_FINE.ACQ_CACHE_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24),0,MOD(TRUNC((ACQUISIZIONE_CACHE_FINE.ACQ_CACHE_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60), 60)||' m. + '||MOD(TRUNC((ACQUISIZIONE_CACHE_FINE.ACQ_CACHE_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60 * 60), 60)||' s.',TRUNC((ACQUISIZIONE_CACHE_FINE.ACQ_CACHE_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24)||' h. + '||MOD(TRUNC((ACQUISIZIONE_CACHE_FINE.ACQ_CACHE_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60), 60)||' m. + '||MOD(TRUNC((ACQUISIZIONE_CACHE_FINE.ACQ_CACHE_DATA_FINE - ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO) * 24 * 60 * 60), 60)||' s.')   ACQ_DURATA
FROM (SELECT
      HIS.ID_LOG           ACQ_ID_LOG,
      HIS.data_attivita    ACQ_DATA_INIZIO,
      HIS.id_utente        ACQ_ID_OPERATORE,
      UTE.NOME||' '||UTE.COGNOME    ACQ_OPERATORE
      FROM APPL_RINF_EVO.LOG_HISTORY    HIS
      JOIN RINF_SICUREZZA_EVO.ANAG_UTENTE   UTE  ON (HIS.ID_UTENTE = UTE.ID_UTENTE)
      WHERE HIS.TESTO LIKE '%è stato lanciato un ciclo di acquisizione!%')   ACQUISIZIONE_INIZIO
LEFT OUTER JOIN (SELECT
                 HIS.data_attivita     ACQ_STEP1_DATA_FINE
                 FROM APPL_RINF_EVO.LOG_HISTORY    HIS
                 WHERE HIS.TESTO LIKE '%Ciclo di acquisizione STEP 1 completato%')  ACQUISIZIONE_STEP_1
ON (TO_CHAR(ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO,'YYYYMMDD') = TO_CHAR(ACQUISIZIONE_STEP_1.ACQ_STEP1_DATA_FINE,'YYYYMMDD'))
/*
LEFT OUTER JOIN (SELECT
                 HIS.data_attivita     ACQ_CONTROLLI_DATA_INIZIO
                 FROM APPL_RINF_EVO.LOG_HISTORY    HIS
                 WHERE HIS.TESTO LIKE '%Sto lanciando i controlli%')   ACQUISIZIONE_CONTROLLI_INIZIO
ON (TO_CHAR(ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO,'YYYYMMDD') = TO_CHAR(ACQUISIZIONE_CONTROLLI_INIZIO.ACQ_CONTROLLI_DATA_INIZIO,'YYYYMMDD'))
*/
LEFT OUTER JOIN (SELECT
                 HIS.data_attivita     ACQ_CONTROLLI_DATA_FINE
                 FROM APPL_RINF_EVO.LOG_HISTORY    HIS
                 WHERE HIS.TESTO LIKE '%I controlli sono terminati%')  ACQUISIZIONE_CONTROLLI_FINE
ON (TO_CHAR(ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO,'YYYYMMDD') = TO_CHAR(ACQUISIZIONE_CONTROLLI_FINE.ACQ_CONTROLLI_DATA_FINE,'YYYYMMDD'))
LEFT OUTER JOIN (SELECT
                 HIS.data_attivita     ACQ_DATA_FINE
                 FROM APPL_RINF_EVO.LOG_HISTORY    HIS
                 WHERE HIS.TESTO LIKE '%L''acquisizione è terminata con esito%')    ACQUISIZIONE_FINE
ON (TO_CHAR(ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO,'YYYYMMDD') = TO_CHAR(ACQUISIZIONE_FINE.ACQ_DATA_FINE,'YYYYMMDD'))
LEFT OUTER JOIN (SELECT
                 HIS.data_attivita     ACQ_CACHE_DATA_FINE
                 FROM APPL_RINF_EVO.LOG_HISTORY    HIS
                 WHERE HIS.TESTO LIKE '%La generazione della cache è terminata%')   ACQUISIZIONE_CACHE_FINE
ON (TO_CHAR(ACQUISIZIONE_INIZIO.ACQ_DATA_INIZIO,'YYYYMMDD') = TO_CHAR(ACQUISIZIONE_CACHE_FINE.ACQ_CACHE_DATA_FINE,'YYYYMMDD'))
ORDER BY ACQUISIZIONE_INIZIO.ACQ_ID_LOG DESC;
