--
-- SCHEMA_MATADATA_VIEW  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.SCHEMA_MATADATA_VIEW
(OWNER, OBJECT_TYPE, OBJECT_NAME, OBJECT_ID, LAST_DDL_TIME, 
 META_LENGTH, META_DATA)
BEQUEATH DEFINER
AS 
SELECT "OWNER","OBJECT_TYPE","OBJECT_NAME","OBJECT_ID","LAST_DDL_TIME","META_LENGTH","META_DATA" FROM (
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, OBJECT_ID, LAST_DDL_TIME, LENGTH(SYS.DBMS_METADATA.GET_DDL(object_type, object_name)) META_LENGTH, SYS.DBMS_METADATA.GET_DDL(object_type, object_name) META_DATA
FROM ALL_OBJECTS
WHERE OBJECT_TYPE IN ('TABLE', 'VIEW', 'PROCEDURE', 'FUNCTION', 'PACKAGE', 'PACKAGE_BODY', 'TRIGGER', 'INDEX', 'SEQUENCE', 'SYNONYM') --
AND OWNER = 'APPL_RINF_EVO'
UNION ALL
SELECT JOB_CREATOR OWNER, JOB_TYPE OBJECT_TYPE, JOB_NAME OBJECT_NAME, NULL OBJECT_ID, NULL LAST_DDL_TIME, LENGTH(SYS.DBMS_METADATA.GET_DDL('PROCOBJ', job_name)) META_LENGTH, SYS.DBMS_METADATA.GET_DDL('PROCOBJ', job_name) META_DATA
FROM USER_SCHEDULER_JOBS
WHERE JOB_CREATOR = 'APPL_RINF_EVO'
) ORDER BY 2, 3;
