--
-- V_ACQUISIZIONE_DATI_V082  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_ACQUISIZIONE_DATI_V082
(CODICE_ACQUISIZIONE, DATA_ACQUISIZIONE, DESCRIZIONE_DSS, CODICE_ESITO, ESITO, 
 STEP)
BEQUEATH DEFINER
AS 
SELECT CODICE_ACQUISIZIONE,
          DATA_ACQUISIZIONE,
          DESCRIZIONE_DSS,
          e.CODICE_ESITO,
          e.DESCRIZIONE esito,
          2 STEP
     FROM RINF_LAVORAZIONE_EVO.ACQUISIZIONE_DATI a,
          RINF_ANAGRAFICHE_EVO.ANAG_ESITO e,
          RINF_LAVORAZIONE_EVO.ANAG_SISTEMI s
    WHERE a.CODICE_ESITO = e.CODICE_ESITO AND a.codice_DSS = s.CODICE_DSS;
