--
-- V_ACQUISIZIONE_DATI_SF_V082  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_ACQUISIZIONE_DATI_SF_V082
(CODICE_ACQUISIZIONE, DATA_ACQUISIZIONE, DESCRIZIONE_DSS, CODICE_ESITO, ESITO, 
 FILE_NAME, ESTENSIONE_FILE, FILE_LOG)
BEQUEATH DEFINER
AS 
SELECT a.CODICE_ACQUISIZIONE,
          DATA_ACQUISIZIONE,
          DESCRIZIONE_DSS,
          e.CODICE_ESITO,
          e.DESCRIZIONE esito,
          FILE_NAME,
          ESTENSIONE_FILE,
          f.document file_log
     FROM RINF_LAVORAZIONE_EVO.ACQUISIZIONE_DATI a,
          RINF_ANAGRAFICHE_EVO.ANAG_ESITO e,
          RINF_LAVORAZIONE_EVO.ANAG_SISTEMI s,
          DOCS_RINF_EVO.ACQUISIZIONE_DATI_SF f
    WHERE     a.CODICE_ESITO = e.CODICE_ESITO
          AND a.codice_DSS = s.CODICE_DSS
          AND a.CODICE_ACQUISIZIONE = f.CODICE_ACQUISIZIONE
          AND CODICE_LOG = 2;
