--
-- V_ANAGRAFICA_LINGUE  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_ANAGRAFICA_LINGUE
(CODICE_LINGUA, SIGLA_LINGUA, DESCRIZIONE, LINGUA_DEFAULT)
BEQUEATH DEFINER
AS 
SELECT CODICE_LINGUA,
          SIGLA_LINGUA,
          DESCRIZIONE,
          LINGUA_DEFAULT
     FROM RINF_ANAGRAFICHE_EVO.ANAG_LINGUA;
