--
-- V_CARICAMENTO_DATI_SF_V082  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_CARICAMENTO_DATI_SF_V082
(CODICE_CARICAMENTO, DATA_CARICAMENTO, CODICE_ESITO, ESITO, DATA_ACQUISIZIONE, 
 FILE_NAME, ESTENSIONE_FILE, FILE_LOG)
BEQUEATH DEFINER
AS 
SELECT a.CODICE_CARICAMENTO,
          DATA_CARICAMENTO,
          e.CODICE_ESITO,
          e.DESCRIZIONE esito,
          DATA_ACQUISIZIONE,
          FILE_NAME,
          ESTENSIONE_FILE,
          f.document file_log
     FROM RINF_STAGING_EVO.ANAG_CARICAMENTI a,
          RINF_ANAGRAFICHE_EVO.ANAG_ESITO e,
          DOCS_RINF_EVO.ANAG_CARICAMENTI_SF f
    WHERE     a.CODICE_ESITO = e.CODICE_ESITO
          AND a.CODICE_CARICAMENTO = f.CODICE_CARICAMENTO;
