--
-- V_CARICAMENTO_DATI  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_CARICAMENTO_DATI
(CODICE_CARICAMENTO, DATA_CARICAMENTO, CODICE_ESITO, ESITO, DATA_ACQUISIZIONE, 
 STEP)
BEQUEATH DEFINER
AS 
SELECT CODICE_CARICAMENTO,
          DATA_CARICAMENTO,
          e.CODICE_ESITO,
          e.DESCRIZIONE esito,
          DATA_ACQUISIZIONE,
          1 STEP
     FROM RINF_STAGING_EVO.ANAG_CARICAMENTI a,
          RINF_ANAGRAFICHE_EVO.ANAG_ESITO e
    WHERE a.CODICE_ESITO = e.CODICE_ESITO;
