--
-- V_CONTROLLO_DATI_V082  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_CONTROLLO_DATI_V082
(CODICE_CONTROLLO, DATA_CONTROLLO, CODICE_ACQUISIZIONE, MODALITA)
BEQUEATH DEFINER
AS 
SELECT CODICE_CONTROLLO,
          DATA_CONTROLLO,
          CODICE_ACQUISIZIONE,
          DESCRIZIONE MODALITA
     FROM RINF_LAVORAZIONE_EVO.CONTROLLO_DATI a,
          RINF_ANAGRAFICHE_EVO.ANAG_MODALITA e
    WHERE a.CODICE_MODALITA = e.CODICE_MODALITA;
