--
-- V_DETTAGLIO_OP_ACCETTATE_V082  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_DETTAGLIO_OP_ACCETTATE_V082
(CODICE_ACQUISIZIONE, CODICE_DTP, DTP, CODICE_SOL_PO, DESCRIZIONE)
BEQUEATH DEFINER
AS 
SELECT CODICE_ACQUISIZIONE,
          o.CODICE_DTP,
          D.DESCRIZIONE dtp,
          CODICE_SOL_PO,
          o.DESCRIZIONE
     FROM RINF_LAVORAZIONE_EVO.OGGETTI_ACQUISITI o,
          RINF_ANAGRAFICHE_EVO.ANAG_DTP d
    WHERE d.CODICE_DTP = o.CODICE_DTP AND CODICE_SOL_PO LIKE 'LO%';
