--
-- V_DETTAGLIO_SOL_SCARTATE_V082  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_DETTAGLIO_SOL_SCARTATE_V082
(CODICE_ACQUISIZIONE, CODICE_DTP, DTP, CODICE_SOL_PO, DESCRIZIONE)
BEQUEATH DEFINER
AS 
SELECT DISTINCT CODICE_ACQUISIZIONE,
                   o.CODICE_DTP,
                   D.DESCRIZIONE dtp,
                   CODICE_SOL_PO,
                   o.NOME_SOL_PO DESCRIZIONE
     FROM RINF_LAVORAZIONE_EVO.scarti_acquisizione o,
          rinf_anagrafiche_EVO.anag_dtp d
    WHERE d.codice_dtp = o.codice_dtp AND CODICE_SOL_PO LIKE 'TR%';
