--
-- V_DETT_CONTROLLI_FALLITI_V082  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_DETT_CONTROLLI_FALLITI_V082
(CODICE_CONTROLLO, CODICE_DTP, NOME_DTP, CODICE_SOL_PO, NOME_SOL_OP, 
 CODICE_ERA, SEDE_TECNICA, NOME_SEDE_TECNICA, CODICE_PARAMETRO, NUMERO_PARAMETRO, 
 DEFINIZIONE_PARAMETRO, SIGLA_VISTA, CODICE_ESITO, ESITO, CODICE_TIPO_CONTROLLO, 
 DEFINIZIONE_TIPO_CONTROLLO, ANOMALIA, VALORE_ERRATO, DATA_CONTROLLO_ERRATO, DATA_ACQUISIZIONE_ERRATO, 
 VALORE_CORRETTO, DATA_CONTROLLO_CORRETTO, DATA_ACQUISIZIONE_CORRETTO, SIGLA_TIPO_DEPOSITARIO, TIPO_DEPOSITARIO)
BEQUEATH DEFINER
AS 
Select  d.CODICE_CONTROLLO,
          d.codice_dtp,
          d.nome_dtp,
          d.CODICE_SOL_PO,
          d.nome_sol_op,
          d.codice_era,
          d.SEDE_TECNICA,
          D.nome_sede_tecnica,
          d.CODICE_PARAMETRO,
          d.NUMERO_PARAMETRO,
          d.DEFINIZIONE_PARAMETRO,
          d.SIGLA_VISTA,
          d.ESITO_CONTROLLO CODICE_ESITO,
          d.DESCRIZIONE_ESITO ESITO,
          d.CODICE_TIPO_CONTROLLO,
          d.Definizione_tipo_controllo,
          d.ANOMALIA,
          d.VALORE_NUOVO VALORE_ERRATO,
          d.DATA_CONTROLLO_NUOVO DATA_CONTROLLO_ERRATO,
          d.DATA_ACQUISIZIONE_NUOVO DATA_ACQUISIZIONE_ERRATO,
          d.VALORE_PRECEDENTE VALORE_CORRETTO,
          d.DATA_CONTROLLO_PRECEDENTE DATA_CONTROLLO_CORRETTO,
          d.DATA_ACQUISIZIONE_PRECEDENTE DATA_ACQUISIZIONE_CORRETTO,
          d.SIGLA_TIPO_DEPOSITARIO,
          d.TIPO_DEPOSITARIO
     From RINF_LAVORAZIONE_EVO.RAPPORTO_CONTROLLI d,
          RINF_ANAGRAFICHE_EVO.CATALOGO_PARAMETRI cp
    Where d.CODICE_PARAMETRO = cp.CODICE_PARAMETRO
      And d.DATA_CONTROLLO_NUOVO between cp.DATA_INIZIO_VALIDITA and cp.DATA_FINE_VALIDITA
      And d.ESITO_CONTROLLO = 0;
