--
-- V_OGGETTI_DA_CONTROLLARE_V082  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_OGGETTI_DA_CONTROLLARE_V082
(CODICE_ACQUISIZIONE, DATA_ACQUISIZIONE, CODICE_DTP, DTP, OP_DA_CONTROLLARE, 
 SOL_DA_CONTROLLARE)
BEQUEATH DEFINER
AS 
SELECT a.CODICE_ACQUISIZIONE,
          a.DATA_ACQUISIZIONE,
          d.CODICE_DTP,
          d.DESCRIZIONE DTP,
          buoni_OP.accettati OP_da_CONTROLLARE,
          NVL (buoni_SOL.accettati, 0) SOL_da_CONTROLLARE
     FROM (  SELECT CODICE_ACQUISIZIONE, CODICE_DTP, COUNT (*) Accettati
               FROM RINF_LAVORAZIONE_EVO.OGGETTI_ACQUISITI
              WHERE SUBSTR (CODICE_SOL_PO, 1, 2) = 'LO'
           GROUP BY CODICE_ACQUISIZIONE, CODICE_DTP) buoni_OP,
          (  SELECT CODICE_ACQUISIZIONE, CODICE_DTP, COUNT (*) Accettati
               FROM RINF_LAVORAZIONE_EVO.OGGETTI_ACQUISITI
              WHERE SUBSTR (CODICE_SOL_PO, 1, 2) = 'TR'
           GROUP BY CODICE_ACQUISIZIONE, CODICE_DTP) buoni_SOL,
          RINF_ANAGRAFICHE_EVO.ANAG_DTP d,
          RINF_LAVORAZIONE_EVO.ACQUISIZIONE_DATI a
    WHERE     buoni_OP.CODICE_ACQUISIZIONE = buoni_SOL.CODICE_ACQUISIZIONE(+)
          AND buoni_OP.CODICE_DTP = buoni_SOL.CODICE_DTP(+)
          AND d.codice_dtp = buoni_OP.codice_dtp
          AND buoni_OP.CODICE_ACQUISIZIONE = a.CODICE_ACQUISIZIONE
   UNION
   SELECT a.CODICE_ACQUISIZIONE,
          a.DATA_ACQUISIZIONE,
          d.CODICE_DTP,
          d.DESCRIZIONE DTP,
          NVL (buoni_OP.accettati, 0) OP_da_CONTROLLARE,
          buoni_SOL.accettati SOL_da_CONTROLLARE
     FROM (  SELECT CODICE_ACQUISIZIONE, CODICE_DTP, COUNT (*) Accettati
               FROM RINF_LAVORAZIONE_EVO.OGGETTI_ACQUISITI
              WHERE SUBSTR (CODICE_SOL_PO, 1, 2) = 'LO'
           GROUP BY CODICE_ACQUISIZIONE, CODICE_DTP) buoni_OP,
          (  SELECT CODICE_ACQUISIZIONE, CODICE_DTP, COUNT (*) Accettati
               FROM RINF_LAVORAZIONE_EVO.OGGETTI_ACQUISITI
              WHERE SUBSTR (CODICE_SOL_PO, 1, 2) = 'TR'
           GROUP BY CODICE_ACQUISIZIONE, CODICE_DTP) buoni_SOL,
          RINF_ANAGRAFICHE_EVO.ANAG_DTP d,
          RINF_LAVORAZIONE_EVO.ACQUISIZIONE_DATI a
    WHERE     buoni_SOL.CODICE_ACQUISIZIONE = buoni_OP.CODICE_ACQUISIZIONE(+)
          AND buoni_SOL.CODICE_DTP = buoni_OP.CODICE_DTP(+)
          AND d.codice_dtp = buoni_SOL.codice_dtp
          AND buoni_SOL.CODICE_ACQUISIZIONE = a.CODICE_ACQUISIZIONE;
