--
-- V_OP_CONTESTO_GEOGRAFICO  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_OP_CONTESTO_GEOGRAFICO
(CODICE_CONTESTO, CONTESTO, CODICE, DESCRIZIONE, SEDE_TECNICA)
BEQUEATH DEFINER
AS 
SELECT c.codice_contesto,
          c.DESCRIZIONE contesto,
          TO_CHAR (r.CODICE_CORRIDOIO) codice,
          r.DEFINIZIONE descrizione,
          l.SEDE_TECNICA
     FROM RINF_CONTROLLATI_EVO.CORRIDOIO_PO l,
          RINF_ANAGRAFICHE_EVO.ANAG_CORRIDOI t,
          RINF_ANAGRAFICHE_EVO.CORRIDOI_633 r,
          RINF_ANAGRAFICHE_EVO.ANAG_CONTESTO_GEO c
    WHERE     c.codice_contesto = 3
          AND r.CODICE_CORRIDOIO = t.CODICE_CORRIDOIO_633
          AND l.codice_corridoio = t.CODICE_GIURISDIZIONE
   UNION
   --Linea Ten-T
   SELECT g.CODICE_CONTESTO,
          g.DESCRIZIONE contesto,
          TO_CHAR (t.CODICE_LINEA_TENT),
          t.NOME_LINEA_TENT descrizione,
          c.SEDE_TECNICA
     FROM RINF_CONTROLLATI_EVO.LINEE_TENT_PO c,
          RINF_ANAGRAFICHE_EVO.ANAG_LINEE_TENT t,
          RINF_ANAGRAFICHE_EVO.ANAG_CONTESTO_GEO g
    WHERE     g.codice_contesto = 4
          AND c.CODICE_LINEA_TENT = t.CODICE_GIURISDIZIONE
   UNION
   --Linea Commerciale
   SELECT g.CODICE_CONTESTO,
          g.DESCRIZIONE contesto,
          h.SIGLA_LINEA_COMMERCIALE,
          h.DEFINIZIONE,
          l.SEDE_TECNICA
     FROM RINF_CONTROLLATI_EVO.LINEA_COMM_PO l,
          RINF_ANAGRAFICHE_EVO.ANAG_LINEA_COMMERCIALE h,
          RINF_ANAGRAFICHE_EVO.ANAG_CONTESTO_GEO g
    WHERE     g.codice_contesto = 5
          AND h.CODICE_GIURISDIZIONE = l.CODICE_GIURISDIZIONE
   UNION
   --Linea Tecnica
   SELECT c.codice_contesto,
          c.DESCRIZIONE contesto,
          CODICE_LINEA_TECNICA,
          t.DESCRIZIONE,
          l.SEDE_TECNICA
     FROM RINF_CONTROLLATI_EVO.PUNTI_OPERATIVI l,
          RINF_ANAGRAFICHE_EVO.ANAG_LINEA_TECNICA t,
          RINF_ANAGRAFICHE_EVO.ANAG_CONTESTO_GEO c
    WHERE c.codice_contesto = 6 AND l.CODICE_LINEA_TECNICA = t.LT_ID
   UNION
   --Linea FCL
   SELECT DISTINCT
          g.CODICE_CONTESTO,
          g.DESCRIZIONE contesto,
             'FL '
          || TO_CHAR (f.FASCICOLO_LINEA)
          || ' ('
          || t.CODICE_LINEA_FCL
          || ')',
          t.DEFINIZIONE,
          LOCALITA_INIZIO SEDE_TECNICA
     FROM RINF_CONTROLLATI_EVO.LINEA_FCL_SOL c,
          RINF_ANAGRAFICHE_EVO.FASCICOLO_LINEE_FCL fl,
          RINF_ANAGRAFICHE_EVO.ANAG_FASCICOLO_LINEE f,
          RINF_CONTROLLATI_EVO.SEZIONI_LINEA s,
          RINF_ANAGRAFICHE_EVO.ANAG_LINEA_FCL t,
          RINF_ANAGRAFICHE_EVO.ANAG_CONTESTO_GEO g
    WHERE     g.codice_contesto = 7
          AND c.CODICE_LINEA_FCL = t.CODICE_LINEA_FCL
          AND s.SEDE_TECNICA = c.SEDE_TECNICA
          AND c.CODICE_LINEA_FCL = fl.CODICE_LINEA_FCL
          AND fl.CODICE_FASCICOLO = f.CODICE_FASCICOLO
   UNION
   SELECT DISTINCT
          g.CODICE_CONTESTO,
          g.DESCRIZIONE contesto,
             'FL '
          || TO_CHAR (f.FASCICOLO_LINEA)
          || ' ('
          || t.CODICE_LINEA_FCL
          || ')',
          t.DEFINIZIONE,
          LOCALITA_FINE SEDE_TECNICA
     FROM RINF_CONTROLLATI_EVO.LINEA_FCL_SOL c,
          RINF_ANAGRAFICHE_EVO.FASCICOLO_LINEE_FCL fl,
          RINF_ANAGRAFICHE_EVO.ANAG_FASCICOLO_LINEE f,
          RINF_CONTROLLATI_EVO.SEZIONI_LINEA s,
          RINF_ANAGRAFICHE_EVO.ANAG_LINEA_FCL t,
          RINF_ANAGRAFICHE_EVO.ANAG_CONTESTO_GEO g
    WHERE     g.codice_contesto = 7
          AND c.CODICE_LINEA_FCL = t.CODICE_LINEA_FCL
          AND s.SEDE_TECNICA = c.SEDE_TECNICA
          AND c.CODICE_LINEA_FCL = fl.CODICE_LINEA_FCL
          AND fl.CODICE_FASCICOLO = f.CODICE_FASCICOLO
   UNION
   --DTP
   SELECT c.codice_contesto,
          c.DESCRIZIONE contesto,
          l.CODICE_DTP,
          t.DESCRIZIONE,
          l.SEDE_TECNICA
     FROM RINF_CONTROLLATI_EVO.PUNTI_OPERATIVI l,
          RINF_ANAGRAFICHE_EVO.ANAG_DTP t,
          RINF_ANAGRAFICHE_EVO.ANAG_CONTESTO_GEO c
    WHERE c.codice_contesto = 8 AND t.CODICE_DTP = l.CODICE_DTP
   UNION
   --Fascicolo Linea
   SELECT DISTINCT g.CODICE_CONTESTO,
                   g.DESCRIZIONE contesto,
                   'FL ' || TO_CHAR (f.FASCICOLO_LINEA),
                   f.DEFINIZIONE,
                   t.LOCALITA_INIZIO SEDE_TECNICA
     FROM RINF_CONTROLLATI_EVO.FASCICOLO_SOL c,
          RINF_ANAGRAFICHE_EVO.ANAG_FASCICOLO_LINEE f,
          RINF_ANAGRAFICHE_EVO.ANAG_CONTESTO_GEO g,
          RINF_CONTROLLATI_EVO.SEZIONI_LINEA t
    WHERE     g.codice_contesto = 10
          AND c.CODICE_FASCICOLO = f.CODICE_FASCICOLO
          AND c.SEDE_TECNICA = t.SEDE_TECNICA
          AND f.FLAG_DISPARI = 1
   UNION
   SELECT DISTINCT g.CODICE_CONTESTO,
                   g.DESCRIZIONE contesto,
                   'FL ' || TO_CHAR (f.FASCICOLO_LINEA),
                   f.DEFINIZIONE,
                   t.LOCALITA_FINE SEDE_TECNICA
     FROM RINF_CONTROLLATI_EVO.FASCICOLO_SOL c,
          RINF_ANAGRAFICHE_EVO.ANAG_FASCICOLO_LINEE f,
          RINF_ANAGRAFICHE_EVO.ANAG_CONTESTO_GEO g,
          RINF_CONTROLLATI_EVO.SEZIONI_LINEA t
    WHERE     g.codice_contesto = 10
          AND c.CODICE_FASCICOLO = f.CODICE_FASCICOLO
          AND c.SEDE_TECNICA = t.SEDE_TECNICA
          AND f.FLAG_DISPARI = 1;
