--
-- V_RICHIESTE_INFORMAZIONE  (View) 
--
CREATE OR REPLACE VIEW APPL_RINF_EVO.V_RICHIESTE_INFORMAZIONE
(CODICE_RICHIESTA, DATA_RICHIESTA, ID_UTENTE, CODICE_UTENTE, COGNOME, 
 NOME, OGGETTO, TESTO, EMAIL_MITTENTE, CODICE_PRIORITA, 
 PRIORITA, CODICE_STATO, STATO, CODICE_TIPO, TIPO, 
 DATA_EVASIONE)
BEQUEATH DEFINER
AS 
SELECT r.CODICE_RICHIESTA,
          r.DATA_RICHIESTA,
          r.ID_UTENTE,
          U.CODICE_UTENTE,
          U.COGNOME,
          U.NOME,
          r.OGGETTO,
          r.TESTO,
          r.EMAIL_MITTENTE,
          r.CODICE_PRIORITA,
          P.DESCRIZIONE priorita,
          r.CODICE_STATO,
          s.DESCRIZIONE stato,
          r.CODICE_TIPO,
          t.DESCRIZIONE tipo,
          r.DATA_EVASIONE
     FROM RINF_AMMINISTRAZIONE_EVO.RICHIESTE_INFORMAZIONE r,
          RINF_AMMINISTRAZIONE_EVO.ANAG_PRIORITA p,
          RINF_AMMINISTRAZIONE_EVO.ANAG_STATO_RICHIESTA s,
          RINF_AMMINISTRAZIONE_EVO.ANAG_TIPO_RICHIESTA t,
          RINF_SICUREZZA_EVO.ANAG_UTENTE u
    WHERE     U.ID_UTENTE = r.ID_UTENTE
          AND R.CODICE_PRIORITA = p.CODICE_PRIORITA
          AND R.CODICE_STATO = s.CODICE_STATO
          AND R.CODICE_TIPO = t.CODICE_TIPO;
